package fr.flushfr.crates.objects.error;

public enum ErrorType {
    UNDEFINED,
    INCORRECT_STRING,
    INCORRECT_BOOLEAN,
    INCORRECT_STRINGLIST,
    INCORRECT_INTEGER,
    INCORRECT_MATERIAL_ID,
    INCORRECT_SOUND,
    INCORRECT_UNDEFINED,
    INCORRECT_PARTICLE,
    INCORRECT_FIREWORK_SHAPE,
    AMOUNT_NULL,
    INCORRECT,

}
