license-key: "effeffe"
language: "fr_FR"
permission:
  admin: "crates.admin"
  player: "crates.player"
preview-crates:
  lore-under:
    - "&7Chance: &5%chance%"
hologram:
  colored-animation:
    refreshColorTime: 5
    color-list:
      - "&a"
      - "&c"
      - "&b"
      - "&6"
      - "&e"