language: "fr_FR"
preview-crates:
  lore-under:
    - "&7Chance: &5%chance%"
hologram:
  colored-animation:
    refreshColorTime: 5
    color-list:
      - "&a"
      - "&c"
      - "&b"
      - "&6"
      - "&e"
animations:
  epicsword:
    sword-item-1: 276
    sword-item-2: 283
    particle: "HAPPY_VILLAGER"
    hologram-position: 2
    hologram-on-rolling:
      - "%item%"
      - "&7Chance: &5%chance%%"
    end-animation:
      sound: ""